In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(1, '../')

# 2 Interactive display

In [6]:
import pyFBS
import pandas as pd

In [7]:
view3D = pyFBS.view3D()

In [8]:
stl = pyFBS.example_lab_testbench["STL"]["A"]
mesh = view3D.add_stl(stl,name = "ts",color = "#83afd2")

In [14]:
xlsx = pyFBS.example_lab_testbench["meas"]["xlsx"]

df_sensors = pd.read_excel(xlsx, sheet_name='Sensors_A')
df_impacts = pd.read_excel(xlsx, sheet_name='Impacts_A')
df_vp = pd.read_excel(pos_xlsx, sheet_name='VP_Channels')

### Sensors

In [17]:
view3D.add_acc_dynamic(mesh,predefined = df_sensors)

In [21]:
df_acc_updated = view3D.get_acc_data()

In [23]:
df_chn_updated = pyFBS.utility.generate_channels_from_sensors(df_acc_updated)

# df_acc_from_chn = pyFBS.utility.generate_sensors_from_channels(df_chn_updated)

### Impacts

In [18]:
view3D.add_imp_dynamic(mesh,predefined = df_impacts)

In [11]:
view3D.get_imp_data()

,Name,Description,Type,DirectionLabel,Quantity,Unit,Component,NodeNumber,Grouping,Position_1,Position_2,Position_3,Direction_1,Direction_2,Direction_3
0,Impact 1,None,None,None,None,None,None,None,None,0.0143109,0.207959,0.017,1.58045e-10,1.04855e-10,-1
1,Impact 2,None,None,None,None,None,None,None,None,-0.0189236,0.31811,0.00729185,0.642787,-0.766045,0
2,Impact 3,None,None,None,None,None,None,None,None,-0.112749,0.157749,0.00735692,0.707107,0.707107,0
3,Impact 4,None,None,None,None,None,None,None,None,-0.0839125,0.243174,0.017,0,0,-1
4,Impact 5,None,None,None,None,None,None,None,None,0.03,0.153247,0.00723164,-1,0,0
5,Impact 6,None,None,None,None,None,None,None,None,0.0151714,0.048171,0.017,0,1.70133e-10,-1

### Virtual points

In [12]:
view3D.add_vp_dynamic(mesh,predefined = df_vp)

In [13]:
view3D.get_vp_data()

,Name,Description,Type,DirectionLabel,Quantity,Unit,Component,NodeNumber,Grouping,Position_1,Position_2,Position_3,Orientation_1,Orientation_2,Orientation_3
0,VP 1,None,None,None,None,None,None,None,None,0.0340844,0.348107,0.007,0,0,0

### Output

In [17]:

with pd.ExcelWriter('output_file.xlsx') as writer:  
    df_acc_updated.to_excel(writer, sheet_name='Sensors',index = False)
    df_imp_updated.to_excel(writer, sheet_name='Impacts',index = False)
    df_chn_updated.to_excel(writer, sheet_name='Channels',index = False)