In [1]:
%load_ext autoreload
%autoreload 2

import sys
import pandas as pd
sys.path.insert(1, '../')

In [2]:
import pyFBS
from pyFBS.utility import *
import pickle
import pyvista as pv

In [3]:
view3D = pyFBS.view3D(show_origin = False)

In [4]:
stl = pyFBS.example_lab_testbench["STL"]["A"]

mesh,_ = view3D.add_stl(stl,name = "ts",color = "#D3D3D3")

In [5]:
xlsx = pyFBS.example_lab_testbench["meas"]["xlsx"]

df_sensors = pd.read_excel(xlsx, sheet_name='Sensors_A')
df_sensors

,Name,Description,Type,Size,NodeNumber,Grouping,Quantity,Unit,Position_1,Position_2,Position_3,Orientation_1,Orientation_2,Orientation_3
0,Sensor 1,AM_AB_final,NaN,0.0102,1,100,Acceleration,m/s^2,-0.076519,0.142987,0.0221,0,0,45.165835
1,Sensor 2,AM_AB_final,NaN,0.0102,2,100,Acceleration,m/s^2,-0.041679,0.278838,0.0221,0,0,-50.268469

In [6]:
xlsx = pyFBS.example_lab_testbench["meas"]["xlsx"]

df_impacts = pd.read_excel(xlsx, sheet_name='Impacts_A')
df_impacts

,Name,Description,NodeNumber,Grouping,Quantity,Unit,Position_1,Position_2,Position_3,Direction_1,Direction_2,Direction_3
0,Impact 1,AM_AB_final,1,100,Force,N,0.014311,0.207959,0.017000,0.000000,0.000000e+00,-1
1,Impact 2,AM_AB_final,2,100,Force,N,-0.018924,0.318110,0.007292,0.642787,-7.660450e-01,0
2,Impact 3,AM_AB_final,3,100,Force,N,-0.112749,0.157749,0.007357,0.707107,7.071068e-01,0
3,Impact 4,AM_AB_final,4,100,Force,N,-0.083912,0.243174,0.017000,0.000000,0.000000e+00,-1
4,Impact 5,AM_AB_final,5,100,Force,N,0.030000,0.153247,0.007232,-1.000000,-2.220446e-16,0
5,Impact 6,AM_AB_final,6,100,Force,N,0.015171,0.048171,0.017000,0.000000,0.000000e+00,-1

In [7]:
xlsx = pyFBS.example_lab_testbench["meas"]["xlsx"]

df_vp = pd.read_excel(xlsx, sheet_name='VP_Channels')
df_vp

,Index,NodeNumber,Grouping,Quantity,Unit,Name,Description,Position_1,Position_2,Position_3,Direction_1,Direction_2,Direction_3
0,1,1,1,Acceleration,m/s^2,VP1_ux,NaN,0.038895,0.348107,0.007,0.642788,-0.766044,0
1,2,2,1,Acceleration,m/s^2,VP1_uy,NaN,0.038895,0.348107,0.007,0.766044,0.642788,0
2,3,3,1,Acceleration,m/s^2,VP1_uz,NaN,0.038895,0.348107,0.007,0.000000,0.000000,1
3,4,4,1,Rotational acceleration,rad/s^2,VP1_tx,NaN,0.038895,0.348107,0.007,0.642788,-0.766044,0
4,5,5,1,Rotational acceleration,rad/s^2,VP1_ty,NaN,0.038895,0.348107,0.007,0.766044,0.642788,0
5,6,6,1,Rotational acceleration,rad/s^2,VP1_tz,NaN,0.038895,0.348107,0.007,0.000000,0.000000,1

In [8]:
view3D.add_acc_dynamic(mesh,predefined = df_sensors)

In [9]:
view3D.get_acc_data()

,Name,Description,Type,DirectionLabel,Quantity,Unit,Component,NodeNumber,Grouping,Position_1,Position_2,Position_3,Orientation_1,Orientation_2,Orientation_3
0,Sensor 1,None,None,None,None,None,None,None,None,-0.076519,0.142987,0.022,0,0,45.1658
1,Sensor 2,None,None,None,None,None,None,None,None,-0.0416791,0.278838,0.022,0,0,-50.2685

In [10]:
view3D.add_imp_dynamic(mesh,predefined = df_impacts)

In [11]:
view3D.get_imp_data()

,Name,Description,Type,DirectionLabel,Quantity,Unit,Component,NodeNumber,Grouping,Position_1,Position_2,Position_3,Direction_1,Direction_2,Direction_3
0,Impact 1,None,None,None,None,None,None,None,None,0.0143109,0.207959,0.017,1.58045e-10,1.04855e-10,-1
1,Impact 2,None,None,None,None,None,None,None,None,-0.0189236,0.31811,0.00729185,0.642787,-0.766045,0
2,Impact 3,None,None,None,None,None,None,None,None,-0.112749,0.157749,0.00735692,0.707107,0.707107,0
3,Impact 4,None,None,None,None,None,None,None,None,-0.0839125,0.243174,0.017,0,0,-1
4,Impact 5,None,None,None,None,None,None,None,None,0.03,0.153247,0.00723164,-1,0,0
5,Impact 6,None,None,None,None,None,None,None,None,0.0151714,0.048171,0.017,0,1.70133e-10,-1

In [12]:
view3D.add_vp_dynamic(mesh,predefined = df_vp)

In [13]:
view3D.get_vp_data()

,Name,Description,Type,DirectionLabel,Quantity,Unit,Component,NodeNumber,Grouping,Position_1,Position_2,Position_3,Orientation_1,Orientation_2,Orientation_3
0,VP 1,None,None,None,None,None,None,None,None,0.0340844,0.348107,0.007,0,0,0

In [17]:
with pd.ExcelWriter('output.xlsx') as writer:  
    view3D.get_imp_data().to_excel(writer, sheet_name='Sheet_name_1',index = False)
    #df2.to_excel(writer, sheet_name='Sheet_name_2')